import type { Trade } from '../types'

const mk = (
  id: string,
  symbol: string,
  direction: Trade['direction'],
  date: string,
  entry: number,
  exit: number | null,
  qty: number,
  fees: number,
  setup: string,
  concept: string,
  notes: string,
): Trade => ({
  id,
  symbol,
  direction,
  date,
  entry,
  exit,
  qty,
  fees,
  setup,
  concept,
  notes,
  screenshotId: null,
  createdAt: 0,
})

export const SAMPLE_TRADES: Trade[] = [
  mk(
    'sample-1',
    'NVDA',
    'long',
    '2026-09-04',
    172.4,
    181.05,
    50,
    2,
    'Breakout',
    'Higher-low pullback into 1H bull flag',
    'Bull flag on the 1h after the AI capex headline. Took profit into morning strength; entry plan was clean.',
  ),
  mk(
    'sample-2',
    'AAPL',
    'short',
    '2026-09-02',
    233.1,
    229.85,
    40,
    2,
    'Pullback',
    'Mean-reversion fade at 20D after gap fill',
    'Rejected at the 20d average. Quick scalp — should have sized up, exit was by the book.',
  ),
  mk(
    'sample-3',
    'TSLA',
    'long',
    '2026-08-27',
    396.2,
    383.1,
    30,
    2,
    'Earnings / News',
    'Counter-trend knife catch (no confirmation)',
    'Caught a falling knife into the print. Size was too big for the setup; next time wait for the reclaim.',
  ),
  mk(
    'sample-4',
    'SPY',
    'long',
    '2026-09-01',
    662.35,
    null,
    20,
    1,
    'Breakout',
    'Weekly range expansion',
    'Swing position: weekly range breakout. Trail below the 5-day, scale half at +3%.',
  ),
  mk(
    'sample-5',
    'AMD',
    'short',
    '2026-08-24',
    208.75,
    214.1,
    25,
    2,
    'Other',
    'Fade of failed open drive',
    'Chased a fade at the open with no confirmation. Ruled a loser before entry — process failure, not a market failure.',
  ),
]
